language: python
python: 3.8

services:
- docker

notifications:
  email:
    on_success: never
    on_failure: always

install:
- wget -q https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip && unzip packer_1.5.5_linux_amd64.zip
- python3 -m pip install tox
- ./packer version
- tox --version

script:
- (cd template && ../packer build -var-file=image.pkrvars.json template.pkr.hcl)
- (cd dind && ../packer build -var-file=image.pkrvars.json template.pkr.hcl)
